// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package service

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AccountRegister struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountRegister) Reset()         { *m = AccountRegister{} }
func (m *AccountRegister) String() string { return proto.CompactTextString(m) }
func (*AccountRegister) ProtoMessage()    {}
func (*AccountRegister) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *AccountRegister) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountRegister.Unmarshal(m, b)
}
func (m *AccountRegister) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountRegister.Marshal(b, m, deterministic)
}
func (m *AccountRegister) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountRegister.Merge(m, src)
}
func (m *AccountRegister) XXX_Size() int {
	return xxx_messageInfo_AccountRegister.Size(m)
}
func (m *AccountRegister) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountRegister.DiscardUnknown(m)
}

var xxx_messageInfo_AccountRegister proto.InternalMessageInfo

func (m *AccountRegister) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *AccountRegister) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type RegisterStatus struct {
	Status               string   `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterStatus) Reset()         { *m = RegisterStatus{} }
func (m *RegisterStatus) String() string { return proto.CompactTextString(m) }
func (*RegisterStatus) ProtoMessage()    {}
func (*RegisterStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *RegisterStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterStatus.Unmarshal(m, b)
}
func (m *RegisterStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterStatus.Marshal(b, m, deterministic)
}
func (m *RegisterStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterStatus.Merge(m, src)
}
func (m *RegisterStatus) XXX_Size() int {
	return xxx_messageInfo_RegisterStatus.Size(m)
}
func (m *RegisterStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterStatus.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterStatus proto.InternalMessageInfo

func (m *RegisterStatus) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*AccountRegister)(nil), "account.AccountRegister")
	proto.RegisterType((*RegisterStatus)(nil), "account.RegisterStatus")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 219 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x4e, 0x2d, 0x2a,
	0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4f, 0x4c, 0x4e, 0xce, 0x2f,
	0xcd, 0x2b, 0x91, 0x92, 0x49, 0xcf, 0xcf, 0x4f, 0xcf, 0x49, 0xd5, 0x4f, 0x2c, 0xc8, 0xd4, 0x4f,
	0xcc, 0xcb, 0xcb, 0x2f, 0x49, 0x2c, 0xc9, 0xcc, 0xcf, 0x2b, 0x86, 0x28, 0x53, 0x72, 0xe6, 0xe2,
	0x77, 0x84, 0x28, 0x0c, 0x4a, 0x4d, 0xcf, 0x2c, 0x2e, 0x49, 0x2d, 0x12, 0x92, 0xe2, 0xe2, 0x28,
	0x2d, 0x4e, 0x2d, 0xca, 0x4b, 0xcc, 0x4d, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0xf3,
	0x85, 0x44, 0xb8, 0x58, 0x53, 0x73, 0x13, 0x33, 0x73, 0x24, 0x98, 0xc0, 0x12, 0x10, 0x8e, 0x92,
	0x06, 0x17, 0x1f, 0x4c, 0x77, 0x70, 0x49, 0x62, 0x49, 0x69, 0xb1, 0x90, 0x18, 0x17, 0x5b, 0x31,
	0x98, 0x25, 0xc1, 0x0c, 0x56, 0x08, 0xe5, 0x19, 0x15, 0x70, 0xf1, 0x41, 0xad, 0x73, 0x2e, 0x4a,
	0x4d, 0x2c, 0xc9, 0x2f, 0x12, 0x8a, 0xe3, 0xe2, 0x05, 0x33, 0x53, 0xa1, 0xe2, 0x42, 0x12, 0x7a,
	0x50, 0x97, 0xeb, 0xa1, 0x39, 0x4c, 0x4a, 0x1c, 0x2e, 0x83, 0x6a, 0x9b, 0x92, 0x54, 0xd3, 0xe5,
	0x27, 0x93, 0x99, 0x44, 0x94, 0xf8, 0xf5, 0xcb, 0x0c, 0xf5, 0x13, 0x4b, 0x4b, 0x32, 0xf4, 0x8b,
	0x33, 0xd3, 0xf3, 0x32, 0xf3, 0xac, 0x18, 0xb5, 0x92, 0xd8, 0xc0, 0xfe, 0x34, 0x06, 0x04, 0x00,
	0x00, 0xff, 0xff, 0xee, 0xa2, 0x66, 0x20, 0x1f, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AccountCreatorClient is the client API for AccountCreator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccountCreatorClient interface {
	//定义一个rpc方法，指定请求和响应类型。
	CreateAccount(ctx context.Context, in *AccountRegister, opts ...grpc.CallOption) (*RegisterStatus, error)
}

type accountCreatorClient struct {
	cc *grpc.ClientConn
}

func NewAccountCreatorClient(cc *grpc.ClientConn) AccountCreatorClient {
	return &accountCreatorClient{cc}
}

func (c *accountCreatorClient) CreateAccount(ctx context.Context, in *AccountRegister, opts ...grpc.CallOption) (*RegisterStatus, error) {
	out := new(RegisterStatus)
	err := c.cc.Invoke(ctx, "/account.AccountCreator/CreateAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountCreatorServer is the server API for AccountCreator service.
type AccountCreatorServer interface {
	//定义一个rpc方法，指定请求和响应类型。
	CreateAccount(context.Context, *AccountRegister) (*RegisterStatus, error)
}

func RegisterAccountCreatorServer(s *grpc.Server, srv AccountCreatorServer) {
	s.RegisterService(&_AccountCreator_serviceDesc, srv)
}

func _AccountCreator_CreateAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountRegister)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountCreatorServer).CreateAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.AccountCreator/CreateAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountCreatorServer).CreateAccount(ctx, req.(*AccountRegister))
	}
	return interceptor(ctx, in, info, handler)
}

var _AccountCreator_serviceDesc = grpc.ServiceDesc{
	ServiceName: "account.AccountCreator",
	HandlerType: (*AccountCreatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAccount",
			Handler:    _AccountCreator_CreateAccount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
